
modLoader="javafml" #mandatory
loaderVersion="[1.20,)" #mandatory
license="MIT" # Replace with your actual license (e.g., MIT, All Rights Reserved, etc.)
#issueTrackerURL="https://your.issue.tracker.url/" #optional

[[mods]] #mandatory
modId="highhelper" # Replace with your actual mod ID
version="1.0.0" # Replace with your mod's version
displayName="High Helper" # Replace with your mod's display name
#updateJSONURL="https://your.mod.update.url/updates.json" #optional
#displayURL="https://your.mod.homepage.url/" #optional
#logoFile="examplemod.png" #optional
#credits="Your Name" #optional
authors="Abdulhaq" # Replace with your name or team name

description='''
A helpful Minecraft mod that enhances gameplay by providing useful utilities and features.
''' # Replace with your mod's description

[[dependencies.highhelper]]
modId="forge"
mandatory=true
versionRange="[47.0,)" # Replace with the Forge version range your mod requires
ordering="NONE"
side="BOTH"

[[dependencies.highhelper]]
modId="minecraft"
mandatory=true
versionRange="[1.20,1.21)"
ordering="NONE"
side="BOTH"
